### ISSUE TITLE
Can't find PaintTool object

### ISSUE THREAD

**Issue by ernOho** [defano/jmonet#44]
Hi,
After installing and configuring this library in Intellij via Maven, I have been trying to run the most basic example given in the read_me for a javafx application. After successfully creating a canvas, I was unable to draw on it. 
Because the PaintTool object can't be created, it seems that the PaintTool class does not exist, which I highly doubt. However, I have looked through the source code and still can't find it.

Have I implemented the example wrong, or am I missing other dependencies?

As a javafx beginner, I apologize for this trivial question. 
Kind regards
  
![PaintTool_Question](https://user-images.githubusercontent.com/63116568/165920132-02cc4561-5707-4995-b822-339b7f2a10fc.PNG)

**Comment by defano** [comment]
Hi @ernOho ,

Not your fault! You've found a documentation bug. `PaintTool` was refactored to `Tool`. Change `PaintTool paintbrush =` to `Tool paintbrush =` (and correct your `import` statement) and you should be good to go.

If you'd like to contribute, feel free to open a PR to correct the README; otherwise I'll correct it in the next few days.
